# Generated by Django 4.1 on 2022-10-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img_cover',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
