# Generated by Django 4.1 on 2022-10-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programapp', '0002_profile_img_profile_img_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img_cover',
        ),
    ]
